// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-w-xPsX-Uy8CECQSrzVc6HaUF_bLFpM',
    appId: '1:665598717884:web:156d525a2ec84a0684c5b9',
    messagingSenderId: '665598717884',
    projectId: 'bmi-calculator-2257d',
    authDomain: 'bmi-calculator-2257d.firebaseapp.com',
    storageBucket: 'bmi-calculator-2257d.appspot.com',
    measurementId: 'G-F6CKPMLFWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZIKz9VGai2ioBeGwIo2LPsbltQL9p_o',
    appId: '1:665598717884:android:58943bff5036282684c5b9',
    messagingSenderId: '665598717884',
    projectId: 'bmi-calculator-2257d',
    storageBucket: 'bmi-calculator-2257d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Y-wEjTPBQ6Eyf0mrSl8Pnk4-UXaMvgM',
    appId: '1:665598717884:ios:1e498b213d74f54084c5b9',
    messagingSenderId: '665598717884',
    projectId: 'bmi-calculator-2257d',
    storageBucket: 'bmi-calculator-2257d.appspot.com',
    iosBundleId: 'com.eslamfares.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Y-wEjTPBQ6Eyf0mrSl8Pnk4-UXaMvgM',
    appId: '1:665598717884:ios:1e498b213d74f54084c5b9',
    messagingSenderId: '665598717884',
    projectId: 'bmi-calculator-2257d',
    storageBucket: 'bmi-calculator-2257d.appspot.com',
    iosBundleId: 'com.eslamfares.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-w-xPsX-Uy8CECQSrzVc6HaUF_bLFpM',
    appId: '1:665598717884:web:a1b8a77aac9e037784c5b9',
    messagingSenderId: '665598717884',
    projectId: 'bmi-calculator-2257d',
    authDomain: 'bmi-calculator-2257d.firebaseapp.com',
    storageBucket: 'bmi-calculator-2257d.appspot.com',
    measurementId: 'G-069QZ8WNLJ',
  );
}
